import pptxgen from "pptxgenjs";

// Slide layout built on the same "Onyx" design tokens as generatePdf.ts

export type PptAccent = "Lavender" | "Mint" | "Peach";

export interface PptSlide {
  title: string;
  points: string[];
}

export interface PptData {
  title: string;
  subtitle?: string;
  slides: PptSlide[];
}

export interface PptOptions {
  accent?: PptAccent;
  date?: Date;
}

// pptxgenjs takes hex colors without the leading "#"
const ACCENTS: Record<
  PptAccent,
  { ac: string; ac2: string; ac3: string; acs: string }
> = {
  Lavender: { ac: "C9C2FC", ac2: "9DDBB9", ac3: "F9B9A3", acs: "EEECFF" },
  Mint: { ac: "9DDBB9", ac2: "FAB8AC", ac3: "B6C9FF", acs: "DEF5E8" },
  Peach: { ac: "F9B9A3", ac2: "B6C9FF", ac3: "A6DAAF", acs: "FFE8E0" },
};

const COLOR = {
  ink: "25233A",
  inkStrong: "1D1A30",
  body: "46435C",
  muted: "67637E",
  line: "E2DFEE",
  tile: "F2F0F8",
  card: "F7F6FB",
  white: "FFFFFF",
};

const FONT = "Aptos";

// LAYOUT_WIDE is 13.333 x 7.5 inches
const PAGE = {
  w: 13.333,
  h: 7.5,
  side: 0.6,
  headerY: 0.35,
  footerY: 6.95,
};

const CONTENT_W = PAGE.w - PAGE.side * 2;

const pad2 = (n: number) => String(n).padStart(2, "0");

export const generatePpt = async (
  data: PptData,
  options: PptOptions = {},
): Promise<Buffer> => {
  const accent = ACCENTS[options.accent ?? "Lavender"];
  const dots = [accent.ac, accent.ac2, accent.ac3];
  const date = (options.date ?? new Date()).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "OnyxAI";
  ppt.company = "OnyxAI";
  ppt.title = data.title;
  ppt.subject = data.title;
  ppt.theme = { headFontFace: FONT, bodyFontFace: FONT };

  const slides = (data.slides ?? []).filter((s) => s?.title);

  // ---- Shared pieces ----
  const logo = (slide: pptxgen.Slide, x: number, y: number) => {
    slide.addShape(ppt.ShapeType.ellipse, {
      x,
      y,
      w: 0.26,
      h: 0.26,
      fill: { color: COLOR.ink },
      line: { type: "none" },
    });
    slide.addShape(ppt.ShapeType.ellipse, {
      x: x + 0.05,
      y: y + 0.05,
      w: 0.08,
      h: 0.08,
      fill: { color: accent.ac },
      line: { type: "none" },
    });
    slide.addText("Onyx", {
      x: x + 0.32,
      y: y - 0.04,
      w: 0.7,
      h: 0.34,
      fontFace: FONT,
      fontSize: 14,
      bold: true,
      color: COLOR.ink,
      margin: 0,
      valign: "middle",
    });
  };

  const pill = (
    slide: pptxgen.Slide,
    text: string,
    x: number,
    y: number,
    w: number,
    bg: string,
  ) => {
    slide.addText(text, {
      shape: ppt.ShapeType.roundRect,
      x,
      y,
      w,
      h: 0.26,
      rectRadius: 0.13,
      fill: { color: bg },
      line: { type: "none" },
      fontFace: FONT,
      fontSize: 9,
      bold: true,
      color: COLOR.inkStrong,
      align: "center",
      valign: "middle",
      margin: 0,
    });
  };

  const header = (slide: pptxgen.Slide) => {
    logo(slide, PAGE.side, PAGE.headerY);
    pill(slide, "AI generated", PAGE.side + 1.05, PAGE.headerY, 1.05, accent.ac);
    slide.addText(data.title, {
      x: PAGE.side + 2.4,
      y: PAGE.headerY - 0.02,
      w: CONTENT_W - 2.4,
      h: 0.3,
      fontFace: FONT,
      fontSize: 10,
      color: COLOR.muted,
      align: "right",
      valign: "middle",
      margin: 0,
      fit: "shrink",
    });
    slide.addShape(ppt.ShapeType.line, {
      x: PAGE.side,
      y: PAGE.headerY + 0.45,
      w: CONTENT_W,
      h: 0,
      line: { color: COLOR.line, width: 0.75 },
    });
  };

  const footer = (slide: pptxgen.Slide, page?: string) => {
    slide.addShape(ppt.ShapeType.line, {
      x: PAGE.side,
      y: PAGE.footerY - 0.1,
      w: CONTENT_W,
      h: 0,
      line: { color: COLOR.line, width: 0.75 },
    });
    slide.addShape(ppt.ShapeType.ellipse, {
      x: PAGE.side,
      y: PAGE.footerY + 0.08,
      w: 0.08,
      h: 0.08,
      fill: { color: accent.ac },
      line: { type: "none" },
    });
    slide.addText(
      "Generated by Onyx AI. It can make mistakes — review before sharing.",
      {
        x: PAGE.side + 0.16,
        y: PAGE.footerY,
        w: 7,
        h: 0.25,
        fontFace: FONT,
        fontSize: 9,
        color: COLOR.muted,
        valign: "middle",
        margin: 0,
      },
    );
    if (page) {
      slide.addText(page, {
        x: PAGE.w - PAGE.side - 2,
        y: PAGE.footerY,
        w: 2,
        h: 0.25,
        fontFace: FONT,
        fontSize: 9,
        color: COLOR.muted,
        align: "right",
        valign: "middle",
        margin: 0,
      });
    }
  };

  // ---- Cover ----
  const addCover = () => {
    const slide = ppt.addSlide();
    slide.background = { color: COLOR.white };
    header(slide);

    const top = 1.15;
    const height = 5.45;
    slide.addShape(ppt.ShapeType.roundRect, {
      x: PAGE.side,
      y: top,
      w: CONTENT_W,
      h: height,
      rectRadius: 0.3,
      fill: { color: accent.acs },
      line: { type: "none" },
    });

    // decorative accent dots, echoing the key-point tiles
    [
      { x: 10.2, y: 1.7, s: 1.5, c: accent.ac },
      { x: 11.25, y: 2.95, s: 0.95, c: accent.ac2 },
      { x: 10.05, y: 3.45, s: 0.6, c: accent.ac3 },
    ].forEach(({ x, y, s, c }) =>
      slide.addShape(ppt.ShapeType.ellipse, {
        x,
        y,
        w: s,
        h: s,
        fill: { color: c },
        line: { type: "none" },
      }),
    );

    const textX = PAGE.side + 0.55;
    const textW = 8.6;

    pill(slide, "PRESENTATION", textX, top + 0.55, 1.35, COLOR.white);

    slide.addText(data.title, {
      x: textX,
      y: top + 1.05,
      w: textW,
      h: 2.0,
      fontFace: FONT,
      fontSize: 44,
      bold: true,
      color: COLOR.ink,
      valign: "bottom",
      margin: 0,
      fit: "shrink",
    });

    if (data.subtitle) {
      slide.addText(data.subtitle, {
        x: textX,
        y: top + 3.2,
        w: textW - 1,
        h: 1.0,
        fontFace: FONT,
        fontSize: 18,
        color: COLOR.body,
        valign: "top",
        margin: 0,
        fit: "shrink",
      });
    }

    slide.addText(
      [
        { text: date, options: { color: COLOR.ink, bold: true } },
        {
          text: `   ·   ${slides.length} slides`,
          options: { color: COLOR.muted },
        },
      ],
      {
        x: textX,
        y: top + height - 0.85,
        w: textW,
        h: 0.35,
        fontFace: FONT,
        fontSize: 11,
        valign: "middle",
        margin: 0,
      },
    );

    footer(slide);
  };

  // ---- Content slide: title + key-point tiles ----
  const addContentSlide = (item: PptSlide, index: number, total: number) => {
    const slide = ppt.addSlide();
    slide.background = { color: COLOR.white };
    header(slide);

    slide.addText(`${pad2(index)} / ${pad2(total)}`, {
      x: PAGE.side,
      y: 1.1,
      w: 3,
      h: 0.3,
      fontFace: FONT,
      fontSize: 10,
      bold: true,
      charSpacing: 1,
      color: COLOR.muted,
      margin: 0,
    });

    slide.addText(item.title, {
      x: PAGE.side,
      y: 1.4,
      w: CONTENT_W,
      h: 0.75,
      fontFace: FONT,
      fontSize: 30,
      bold: true,
      color: COLOR.ink,
      valign: "middle",
      margin: 0,
      fit: "shrink",
    });

    const points = (item.points ?? []).filter(Boolean).slice(0, 8);
    const cols = points.length <= 3 ? 1 : 2;
    const rows = Math.ceil(points.length / cols) || 1;
    const gap = 0.2;
    const areaTop = 2.4;
    const areaH = PAGE.footerY - 0.35 - areaTop;
    const tileW = (CONTENT_W - gap * (cols - 1)) / cols;
    const tileH = Math.min((areaH - gap * (rows - 1)) / rows, 1.6);
    const fontSize = rows >= 4 ? 13 : 15;

    points.forEach((point, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = PAGE.side + col * (tileW + gap);
      const y = areaTop + row * (tileH + gap);

      slide.addShape(ppt.ShapeType.roundRect, {
        x,
        y,
        w: tileW,
        h: tileH,
        rectRadius: 0.18,
        fill: { color: COLOR.tile },
        line: { type: "none" },
      });
      slide.addShape(ppt.ShapeType.ellipse, {
        x: x + 0.25,
        y: y + tileH / 2 - 0.07,
        w: 0.14,
        h: 0.14,
        fill: { color: dots[i % dots.length] },
        line: { type: "none" },
      });
      slide.addText(point, {
        x: x + 0.55,
        y: y + 0.08,
        w: tileW - 0.8,
        h: tileH - 0.16,
        fontFace: FONT,
        fontSize,
        color: COLOR.ink,
        valign: "middle",
        margin: 0,
        fit: "shrink",
      });
    });

    footer(slide, `${index + 1}`);
  };

  // ---- Closing ----
  const addThankYouSlide = () => {
    const slide = ppt.addSlide();
    slide.background = { color: COLOR.white };
    header(slide);

    slide.addShape(ppt.ShapeType.roundRect, {
      x: PAGE.side,
      y: 1.15,
      w: CONTENT_W,
      h: 5.45,
      rectRadius: 0.3,
      fill: { color: accent.acs },
      line: { type: "none" },
    });

    dots.forEach((c, i) =>
      slide.addShape(ppt.ShapeType.ellipse, {
        x: PAGE.w / 2 - 0.55 + i * 0.4,
        y: 2.55,
        w: 0.3,
        h: 0.3,
        fill: { color: c },
        line: { type: "none" },
      }),
    );

    slide.addText("Thank you", {
      x: PAGE.side,
      y: 3.0,
      w: CONTENT_W,
      h: 1.1,
      fontFace: FONT,
      fontSize: 48,
      bold: true,
      color: COLOR.ink,
      align: "center",
      valign: "middle",
      margin: 0,
    });

    slide.addText(data.title, {
      x: PAGE.side + 1.5,
      y: 4.1,
      w: CONTENT_W - 3,
      h: 0.6,
      fontFace: FONT,
      fontSize: 16,
      color: COLOR.body,
      align: "center",
      valign: "top",
      margin: 0,
      fit: "shrink",
    });

    footer(slide);
  };

  addCover();
  slides.forEach((s, i) => addContentSlide(s, i + 1, slides.length));
  addThankYouSlide();

  return (await ppt.write({ outputType: "nodebuffer" })) as Buffer;
};
